### ISSUE TITLE
Death Masking different from the paper

### ISSUE THREAD

**Issue by Zarzard** [marlbenchmark/on-policy#1]
Hello! 
I checked your paper and found in section 4.5 that the "death masking" is to simply use an agent-specific
constant vector, i.e., a zero vector with the agent’s ID, as the input to the value function after an agent dies. However, I can't find the corresponding code in this project. You seem to apply "active mask" to the entropy term, not the state. 
Do I miss any important message in this project?

**Comment by akashvelu** [comment]
Hi, thanks for taking a look at our work! We formulate the agent-specific constant vector for dead agents ("death masking") in the environment code itself: please see [here](https://github.com/marlbenchmark/on-policy/blob/121044954756b5317230e30d47e409802991458b/onpolicy/envs/starcraft2/StarCraft2_Env.py#L1327) for the code that does this. The "active_mask" which specifies which agents are active/dead is used in 3 places: the [policy(actor) loss](https://github.com/marlbenchmark/on-policy/blob/121044954756b5317230e30d47e409802991458b/onpolicy/algorithms/r_mappo/r_mappo.py#L125), in [GAE normalization](https://github.com/marlbenchmark/on-policy/blob/121044954756b5317230e30d47e409802991458b/onpolicy/algorithms/r_mappo/r_mappo.py#L175), and in the [entropy term](https://github.com/marlbenchmark/on-policy/blob/121044954756b5317230e30d47e409802991458b/onpolicy/algorithms/utils/act.py#L158). In these last three points of the code, the active mask is used to mask out data in which the corresponding agents are dead.  Please let us know if this clarifies and if there are further questions!

**Comment by Zarzard** [comment]
Got it! Thanks!
