### ISSUE TITLE
Why share_obs in shared/mpe_runner.py just repeats obs when self.use_centralized_V set to true 

### ISSUE THREAD

**Issue by Jaroan** [marlbenchmark/on-policy#104]
Why is share_obs repeating the obs value again for n times when using a centralized V? Code taken from [mpe_runner.py](https://github.com/marlbenchmark/on-policy/blob/d53c4902cf2c291c93ced2c42c621371982ca2eb/onpolicy/runner/shared/mpe_runner.py#L133C1-L137C28)
```
if self.use_centralized_V:
    share_obs = obs.reshape(self.n_rollout_threads, -1)
    share_obs = np.expand_dims(share_obs, 1).repeat(self.num_agents, axis=1)
else:
    share_obs = obs
```
What is share_obs here contributing to in the critic?
Thanks in advance!

**Comment by zoeyuchao** [comment]
It is mappo style. We use the concatenation of all agent observations as the global state in MPE.
