### ISSUE TITLE
求助FP和AS状态！！

### ISSUE THREAD

**Issue by 1999Zzh** [marlbenchmark/on-policy#108]
论文中提到的FP和AS状态，在代码中分别对应着什么？
环境代码中有两种全局状态分别是：get_state和get_state_agent，通过一个--use_state_agent参数控制采用哪个作为价值网络的输入，但很迷惑这两种全局状态哪一个是FP，哪一个是AS？

**Comment by zoeyuchao** [comment]
邮件回复你啦！请查收！
