### ISSUE TITLE
code error about value norm

### ISSUE THREAD

**Issue by hijkzzz** [marlbenchmark/on-policy#12]
In r_mappo.py, line 175

```
        if self._use_popart:
            advantages = buffer.returns[:-1] - self.value_normalizer.denormalize(buffer.value_preds[:-1])
        else:
            advantages = buffer.returns[:-1] - buffer.value_preds[:-1]
```

should be fixed

```
        if self._use_popart or self._use_valuenorm:
            advantages = buffer.returns[:-1] - self.value_normalizer.denormalize(buffer.value_preds[:-1])
        else:
            advantages = buffer.returns[:-1] - buffer.value_preds[:-1]
```

This error collapses the performance of the PPO.

Others

It seems that the paper mentions the use of PopArt, but it is not actually used in the code.
Finally, MAPPO (centralized V) is mentioned in the abstract of the paper, but it is actually IPPO with global information because the value function is not centralized.

Thanks.

**Comment by zoeyuchao** [comment]
Thanks for pointing that, i made this mistake whiling clean the code, but the results are got by the right code.

**Comment by zoeyuchao** [comment]
As for MAPPO&IPPO, we follow the naming convention as maddpg, which is also training separate value function for each agent. More specifically, centralized mean the value functions takes global information rather than learning a single value function shared across all the agents.
