### ISSUE TITLE
Missing base_runner.py in runner/separated

### ISSUE THREAD

**Issue by Henry668** [marlbenchmark/on-policy#14]
Hi~ When I try to run the speaker_listener env, I find the base_runner.py file is missing, could you provide this file? 
Thanks!

**Comment by zoeyuchao** [comment]
I am sorry for missing the file, just upload it.

**Comment by Henry668** [comment]
Hello, I come again to look for the separated_buffer.py, could you please provide this file? 
Thanks!

**Comment by ConstantinosM** [comment]
Hi! The separated_buffer doesn't exist in this repo. I copied the one in the testing repo but it doesn't work. There are some missing parts so the simple speaker listener scenarios cannot run. Any help would be great 🙂!

**Comment by zoeyuchao** [comment]
hey guys, sorry for missing the separated part, just fixed it and u guys can double check. Thanks again for the attention.

**Comment by ConstantinosM** [comment]
Thanks a lot! It seems that there are other missing files though. As I mentioned I copied pasted the `separated_buffer.py` from your testing repo but the modules in separated/base_runner.py ending in `_single` seem missing:

```python
        if "mappo" in self.algorithm_name:
            if self.use_single_network:
                from onpolicy.algorithms.r_mappo_single.r_mappo_single import R_MAPPO as TrainAlgo
                from onpolicy.algorithms.r_mappo_single.algorithm.rMAPPOPolicy import R_MAPPOPolicy as Policy
            else:
                from onpolicy.algorithms.r_mappo.r_mappo import R_MAPPO as TrainAlgo
                from onpolicy.algorithms.r_mappo.algorithm.rMAPPOPolicy import R_MAPPOPolicy as Policy
        elif "mappg" in self.algorithm_name:
            if self.use_single_network:
                from onpolicy.algorithms.r_mappg_single.r_mappg_single import R_MAPPG as TrainAlgo
                from onpolicy.algorithms.r_mappg_single.algorithm.rMAPPGPolicy import R_MAPPGPolicy as Policy
            else:
                from onpolicy.algorithms.r_mappg.r_mappg import R_MAPPG as TrainAlgo
                from onpolicy.algorithms.r_mappg.algorithm.rMAPPGPolicy import R_MAPPGPolicy as Policy
        else:
            raise NotImplementedError
```
Unless I am missing something still I cannot train in speaker-listener scenario.

**Comment by zoeyuchao** [comment]
It seems you make option  "use_single_network" on, which is by default False in on-policy repository. BTW: we don't make other source code public for now, like ppg and single-base.

**Comment by zoeyuchao** [comment]
> Thanks a lot! It seems that there are other missing files though. As I mentioned I copied pasted the `separated_buffer.py` from your testing repo but the modules in separated/base_runner.py ending in `_single` seem missing:
> 
> ```python
>         if "mappo" in self.algorithm_name:
>             if self.use_single_network:
>                 from onpolicy.algorithms.r_mappo_single.r_mappo_single import R_MAPPO as TrainAlgo
>                 from onpolicy.algorithms.r_mappo_single.algorithm.rMAPPOPolicy import R_MAPPOPolicy as Policy
>             else:
>                 from onpolicy.algorithms.r_mappo.r_mappo import R_MAPPO as TrainAlgo
>                 from onpolicy.algorithms.r_mappo.algorithm.rMAPPOPolicy import R_MAPPOPolicy as Policy
>         elif "mappg" in self.algorithm_name:
>             if self.use_single_network:
>                 from onpolicy.algorithms.r_mappg_single.r_mappg_single import R_MAPPG as TrainAlgo
>                 from onpolicy.algorithms.r_mappg_single.algorithm.rMAPPGPolicy import R_MAPPGPolicy as Policy
>             else:
>                 from onpolicy.algorithms.r_mappg.r_mappg import R_MAPPG as TrainAlgo
>                 from onpolicy.algorithms.r_mappg.algorithm.rMAPPGPolicy import R_MAPPGPolicy as Policy
>         else:
>             raise NotImplementedError
> ```
> 
> Unless I am missing something still I cannot train in speaker-listener scenario.

fixed！

**Comment by ConstantinosM** [comment]
Thanks for the file! Have you tested that this repo works fine in simple listener-speaker scenario and separated networks? From the paper: 

> Note that since the two agents in speaker-listener have different observation and action spaces, this is the only setting in this paper where we do not share parameters but train separate policies for each agent.

So setting at the config.py --share_policy=False I get this error: `AttributeError: 'MPERunner' object has no attribute 'use_single_network'`. Looking at the base_runner.py file you submitted in the separated folder there is no attribute `use_single_network`. How can I train in this scenario with separated nets as you did?

**Comment by zoeyuchao** [comment]
i updated the repo, "git pull" and try again.

**Comment by ConstantinosM** [comment]
I am sorry but could you please kindly read carefully what I wrote above 🙂? I have incorporated ALL your recent changes and the `use_single_network` creates problems. It is still there and nowhere else defined! Have you tried to see if this repo can train successfully in speaker-listener scenario AS IS right now?

With a little bit of investigation I am realizing that you had options to use ONE network with Actor and Critic heads but somehow you removed it? So most likely it is a leftover -- it will be good though if we had that option as spatial features can be encoded with one network and then have separate heads. So most likely the `use_single_network` is a leftover from something else.

The only thing that worked was to edit the save and restore functions of the `separated/base_runner.py` as below:

```python
    def save(self):
        for agent_id in range(self.num_agents):
                policy_actor = self.trainer[agent_id].policy.actor
                torch.save(policy_actor.state_dict(), str(self.save_dir) + "/actor_agent" + str(agent_id) + ".pt")
                policy_critic = self.trainer[agent_id].policy.critic
                torch.save(policy_critic.state_dict(), str(self.save_dir) + "/critic_agent" + str(agent_id) + ".pt")
    
    def restore(self):
        for agent_id in range(self.num_agents):
                policy_actor_state_dict = torch.load(str(self.model_dir) + '/actor_agent' + str(agent_id) + '.pt')
                self.policy[agent_id].actor.load_state_dict(policy_actor_state_dict)
                policy_critic_state_dict = torch.load(str(self.model_dir) + '/critic_agent' + str(agent_id) + '.pt')
                self.policy[agent_id].critic.load_state_dict(policy_critic_state_dict)

```

**Comment by ConstantinosM** [comment]
With the above modification i managed to train successfully in speaker-listener scenario. My results:
![image](https://user-images.githubusercontent.com/25111975/122651280-c54afe00-d105-11eb-8f91-89ca333ef8d9.png)

which i think are consistent to what you report in your paper. I noticed that you achieve that score quite faster (~1M steps vs mine 4M steps).

I used: 

- `n_training_threads`: 20
- `n_rollout_threads`: 150

1 GPU GeForce 1080GTX Ti in a 72 CPU machine. Please let me know if I need to modify anything here for faster training.

**Comment by zoeyuchao** [comment]
> I am sorry but could you please kindly read carefully what I wrote above 🙂? I have incorporated ALL your recent changes and the `use_single_network` creates problems. It is still there and nowhere else defined! Have you tried to see if this repo can train successfully in speaker-listener scenario AS IS right now?
> 
> With a little bit of investigation I am realizing that you had options in the code be able to use ONE network with Actor and Critic heads but somehow you removed it? So most likely it is a leftover -- it will be good though if we had that option as spatial features can be encoded with one network and then have separate heads for actor and critic. So most likely the `use_single_network` is a leftover from something else.
> 
> The only thing that worked was to edit the save and restore functions of the `separated/base_runner.py` as below:
> 
> ```python
>     def save(self):
>         for agent_id in range(self.num_agents):
>                 policy_actor = self.trainer[agent_id].policy.actor
>                 torch.save(policy_actor.state_dict(), str(self.save_dir) + "/actor_agent" + str(agent_id) + ".pt")
>                 policy_critic = self.trainer[agent_id].policy.critic
>                 torch.save(policy_critic.state_dict(), str(self.save_dir) + "/critic_agent" + str(agent_id) + ".pt")
>     
>     def restore(self):
>         for agent_id in range(self.num_agents):
>                 policy_actor_state_dict = torch.load(str(self.model_dir) + '/actor_agent' + str(agent_id) + '.pt')
>                 self.policy[agent_id].actor.load_state_dict(policy_actor_state_dict)
>                 policy_critic_state_dict = torch.load(str(self.model_dir) + '/critic_agent' + str(agent_id) + '.pt')
>                 self.policy[agent_id].critic.load_state_dict(policy_critic_state_dict)
> ```

Thanks for pointing that and i have updated the repo again. The reason why i remove the single network code is we didn't use that in our paper.

**Comment by zoeyuchao** [comment]
> With the above modification i managed to train successfully in speaker-listener scenario. My results:
> ![image](https://user-images.githubusercontent.com/25111975/122651280-c54afe00-d105-11eb-8f91-89ca333ef8d9.png)
> 
> which i think are consistent to what you report in your paper. I noticed that you achieve that score quite faster (~1M steps vs mine 4M steps).
> 
> I used:
> 
> * `n_training_threads`: 20
> * `n_rollout_threads`: 150
> 
> 1 GPU GeForce 1080GTX Ti in a 72 CPU machine. Please let me know if I need to modify anything here for faster training.

You can use the same hyper-parameters we reported in the appendix, like 128 n_rollout_threads.

**Comment by ConstantinosM** [comment]
Thanks a lot Chao! Is there any chance that you could share somehow the `single_network` code variation 🙏🏼? The reason for this is that single network offers some architectural flexibility such as additional heads (outputs) to the network, a single loss function etc.

**Comment by zoeyuchao** [comment]
It should be easy to implement that, u can try a little bit. I will release the full version when i finish cleaning code.

**Comment by testMondey** [comment]
I try to create the conda environment and install the dependencies on ubuntu18.04. There are many conflicts in versions. And finnally I get  **RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED** . Have you ever met that? How did you create your environment? 
Then I find the yaml file. Then I use conda env create -f xx.yaml. What's 'mappo' in the yaml file? Should I remove that? 
Thanks a lot!

**Comment by zoeyuchao** [comment]
> I try to create the conda environment and install the dependencies on ubuntu18.04. There are many conflicts in versions. And finnally I get **RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED** . Have you ever met that? How did you create your environment?
> Then I find the yaml file. Then I use conda env create -f xx.yaml. What's 'mappo' in the yaml file? Should I remove that?
> Thanks a lot!

Double check your cuda version and torch vesion, refer to official pytorch website. This on-policy repo. relies on very few packages so i would suggest u to install package one by one instead of using yaml file.

**Comment by testMondey** [comment]
> > I try to create the conda environment and install the dependencies on ubuntu18.04. There are many conflicts in versions. And finnally I get **RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED** . Have you ever met that? How did you create your environment?
> > Then I find the yaml file. Then I use conda env create -f xx.yaml. What's 'mappo' in the yaml file? Should I remove that?
> > Thanks a lot!
> 
> Double check your cuda version and torch vesion, refer to official pytorch website. This on-policy repo. relies on very few packages so i would suggest u to install package one by one instead of using yaml file.

I find the problem : My Graphics card is 3060 which demands cuda11.0+. I always use cuda10.2 so it cannot use cudnn to speed up the training.
