### ISSUE TITLE
How to visualize the .wandb and the others

### ISSUE THREAD

**Issue by liuziwei0322** [marlbenchmark/on-policy#15]
I hope i can visualize the average_episode_rewards,but in this folder I can only see a file named "events.out.tfevents.xxx.amax".I hope i can open this file,is there somewhere i should change? if you can tell me i would be appreciate.
i hope you can tell me how to open .wandb file

**Comment by zoeyuchao** [comment]
if you are using wandb, please follow the instructions from official website: https://docs.wandb.ai/. If you are using tensorboard, here is the user example: https://github.com/lanpa/tensorboardX
