### ISSUE TITLE
TypeError: cannot assign 'torch.FloatTensor' as parameter 'stddev' (torch.nn.Parameter or None expected)

### ISSUE THREAD

**Issue by DosHacker** [marlbenchmark/on-policy#19]
Running  train_mpe

The code reports an error 

Line 63 in the file  "onpolicy/algorithms/utils/popart.py"

        self.stddev = (self.mean_sq - self.mean ** 2).sqrt().clamp(min=1e-4)
        self.weight = self.weight * old_stddev / self.stddev
        self.bias = (old_stddev * self.bias + old_mean - self.mean) / self.stddev

File "/on-policy-main/onpolicy/algorithms/utils/popart.py", line 63, in update
    self.stddev = (self.mean_sq - self.mean ** 2).sqrt().clamp(min=1e-4)
File "/home/cc/anaconda3/envs/MAPPO/lib/python3.6/site-packages/torch/nn/modules/module.py", line 613, in __setattr__
    .format(torch.typename(value), name))
TypeError: cannot assign 'torch.FloatTensor' as parameter 'stddev' (torch.nn.Parameter or None expected)

Whether the above code needs to be changed to the following code:

        self.stddev = nn.Parameter((self.mean_sq - self.mean ** 2).sqrt().clamp(min=1e-4))

        self.weight = nn.Parameter(self.weight * old_stddev / self.stddev)
        self.bias = nn.Parameter((old_stddev * self.bias + old_mean - self.mean) / self.stddev)

**Comment by zoeyuchao** [comment]
Thanks for pointing that, it might be a version-caused bug.
