### ISSUE TITLE
Values of Hyperparameters 

### ISSUE THREAD

**Issue by FisherguanbaoYu** [marlbenchmark/on-policy#21]
Could you provide the values of "--use_popart", "--use_valuenorm", "--use_value_active_masks", "--use_policy_active_masks" across all SMAC maps to help better reproduce your results? Thanks a lot!

**Comment by zoeyuchao** [comment]
popart False 
valuenorm True
use_value_active_masks False
use_policy_active_masks True

**Comment by FisherguanbaoYu** [comment]
Thanks for comment. So value_active_masks are not used in any maps?
