### ISSUE TITLE
QMIX performance in Hanabi

### ISSUE THREAD

**Issue by 51616** [marlbenchmark/on-policy#22]
I read and learn interesting insights from the MAPPO paper. I have a few questions regarding the paper (and its previous version).

I saw the performance of QMIX in Hanabi reported in a previous version of the paper which was very low (0.29 in small version). I'm curious why it performed so badly? The results reported in the current version with VDN performs way better despite QMIX being superset of VDN. I understand that the current paper use the full version of the game, still, its score almost reaches the optimum while QMIX (in small version) doesn't seem to learn meaningful policy. Is it possible to get similar performance to VDN using QMIX?

**Comment by zoeyuchao** [comment]
The result of VDN is taken from other papers，we did not reproduce the performance via naive QMIX or VDN. The biggest difference is we did not adopt the distributed training manner in my opinion. You can look up to their papers for more details. The large batchsize of training data seems critical in hanabi domain.

**Comment by 51616** [comment]
Thank you for the information :)
