### ISSUE TITLE
Is MAPPO similar or same with the Parameter sharing framework in one earlier work?

### ISSUE THREAD

**Issue by LINGYUNFDU** [marlbenchmark/on-policy#23]
Hi, 
Thanks for your work! But I am a bit confused about whether the MAPPO is the same as the "parameter sharing framework" proposed in "http://ala2017.it.nuigalway.ie/papers/ALA2017_Gupta.pdf"? That is published in 2017, maybe in your great paper should refer to this work or compare it. 

thanks!

**Comment by zoeyuchao** [comment]
Parameters sharing is a common setting for MARL and we follow that. MAPPO focuses on the ppo’s performance of multi-agent variant, and we also give 5 implementation advices for MARL researchers.
