### ISSUE TITLE
W & B errors about running train_mpe

### ISSUE THREAD

**Issue by AI-Hello** [marlbenchmark/on-policy#24]
When running the train_mpe file, prompts W & B, I choose to do not need visual results, but run errors, run this program to use W & B? because I have been using Tensorboard, I haven't used W & B, I don't know how to use it. Whether this program must be used to use W & B, can you join the Tensorboard selection, thank you!

**Comment by zoeyuchao** [comment]
add --use_wandb in train_mpe.sh
