### ISSUE TITLE
在MAPPO中运行MPE的speaker_listener在7个智能体环境中的实验问题

### ISSUE THREAD

**Issue by AI-Hello** [marlbenchmark/on-policy#27]
你好，我想在MAPPO中运行MPE的speaker_listener在7个智能体环境中的实验，但是程序提示我只能支持两个智能体，那么这个代码不支持speaker_listener下7个智能体的实验吗

**Comment by zoeyuchao** [comment]
The speaker_listener scenario doesn't support 7 agents, so i set an assert in the train_mpe.py. u can delete it if u want to change the speaker_listener scenario.
