### ISSUE TITLE
Is seperated runner fully supported?

### ISSUE THREAD

**Issue by xubo92** [marlbenchmark/on-policy#29]
Hi @jxwuyi @eugenevinitsky @zoeyuchao @akashvelu 

Thanks a lot for your great work! It helps a lot in synchronizing the performance of the on-policy DRL algorithm from single to multi-agent cases.

I found out there are some missing files about separated runner working on specific environments (e.g. SMAC or MPE), in the folder "onpolicy/runner/seperated/xxx". But I noticed that there is a base_runner implemented. So I was wondering if the separate runner (maybe plus the separate buffer) is a ready-to-go implementation here with PPO optimization? If so, I can directly use it with my customized environment and run the experiments, similarly to the use of shared runner.

Look forward to your reply! Thanks!

Best,
Xubo

**Comment by zoeyuchao** [comment]
we don't support separated smac runner for now, but we upload a separated mpe runner, u can refer to this one.

**Comment by xubo92** [comment]
Thanks a lot!
