### ISSUE TITLE
AssertionError: check recurrent policy!

### ISSUE THREAD

**Issue by YaoweiFan** [marlbenchmark/on-policy#3]
I have run your code:
```zsh
./train_smac.sh
```
however, the following error occured:
```
env is StarCraft2, map is corridor, algo is mappo, exp is mlp, max seed is 1
seed is 1:
Traceback (most recent call last):
  File "train/train_smac.py", line 175, in <module>
    main(sys.argv[1:])
  File "train/train_smac.py", line 82, in main
    "check recurrent policy!")
AssertionError: check recurrent policy!
```
I changed the argument "algo" in file "tran_smac.sh"
```zsh
algo="rmappo"
```
I don't know whether this modification is suitable or not. It did work, but the results were not satisfactory:
![image](https://user-images.githubusercontent.com/54715057/111400517-722a6f00-8702-11eb-8f6d-7cdb1f1153e5.png)
![image](https://user-images.githubusercontent.com/54715057/111400684-cb929e00-8702-11eb-9e14-7e99dfbb4699.png)

Do you have some good parameters for trainnning?

**Comment by zoeyuchao** [comment]
Let me clarify the meaning of the parameters you mentioned. 1. algo="mappo"  means that we only use mlp-version while algo="rmappo" means we will use recurrent-version. 2. If you use "mappo"（i.e. you write algo=”mappo“ in train_smac.sh）, make sure you turn off the "--use_recurrent_policy" option, which is on by default.  (i.e. you need to add "--use_recurrent_policy" in train_smac.sh) 3. In another word, we use "rmappo“ by default. 4. corridor map uses "mappo", see the appendix for more detailed hyper-parameters.

**Comment by YaoweiFan** [comment]
I get it. Thank you for your reply.

**Comment by ReinholdM** [comment]
Have you reproduced the results in SC2 now? I ever run the exp on the corridor map and obtain almost 100% win_rate but now it's not work in my exp. My commands are the same as you mentioned above.

**Comment by zoeyuchao** [comment]
Sorry, i just figure out why u guys have this problem, i made a mistake while cleaning the code, and i just update the default option in config.py, just FYI.
