### ISSUE TITLE
Centralized-V between IPPO and MAPPO

### ISSUE THREAD

**Issue by xubo92** [marlbenchmark/on-policy#30]
Hi @jxwuyi @eugenevinitsky @zoeyuchao @akashvelu 

Thanks for your work! 

Just a quick question: is turning on or off the **use_centralized_V** only affects if the input is from local observations or the centralized state? Does it affect the structure of actual value network used? from the code what I can see is no matter **use_centralized_V** is true or false, the input size is always (num_agents, input_dim), and the output values are with size (num_agents, 1).  So the networks are not affected by **use_centralized_V**. And centralized value outputs will be the same for "num_agents", right?

Look forward to your reply! Thank you!

Best,
Xubo

**Comment by zoeyuchao** [comment]
Yes, the value network architecture is not affected by use_centralized_V. but i think the first dimension is related to the batch_size instead of num_agents.

**Comment by xubo92** [comment]
Ok, yeah that makes sense! thanks!

**Comment by xubo92** [comment]
Hi @zoeyuchao 

Just a follow-up question, so if I use a separate runner, does that mean each agent has its' own policy and value network? so `n` agents means `n` policy and `n` value networks. And even though I set `use_centralized_V`, that means for each agent's value network, it accepts the same shared observation, and outputs the same value estimation, right? `use_centralized_V` does not mean there is only one value network for all agents (under separate runner), right?

just want to be more clear about this. Thanks!

**Comment by zoeyuchao** [comment]
@xubo92 yes, u are right:)
