### ISSUE TITLE
Metric problem about MAPPO

### ISSUE THREAD

**Issue by PaParaZz1** [marlbenchmark/on-policy#32]
Nice paper and project! And we are also doing some research on this topic. 

We find there is something confused in the original MAPPO paper: why the shadow parts of the following figure in page 7 are more than win rate 1.0? What kind of metric you use in this figure? Can you offer some detailed statements? Thank you!

<img width="248" alt="Screen Shot 2021-12-15 at 7 32 19 PM" src="https://user-images.githubusercontent.com/33195032/146179128-5ef1aaac-5f00-4e3b-bda2-4afa6fcaa389.png">

**Comment by akashvelu** [comment]
Thanks for your interest! We plot the median win-rate for all methods, and the shadowed parts indicate the variance.

**Comment by PaParaZz1** [comment]
OK, thanks for your reply.
