### ISSUE TITLE
About Hanabi Implementation Details

### ISSUE THREAD

**Issue by PeppaCat** [marlbenchmark/on-policy#33]
Why throw away [the reward of step 0](https://github.com/marlbenchmark/on-policy/blob/9677c91ff7de0defc245f65c1ea31c8587df162a/onpolicy/runner/shared/hanabi_runner_forward.py#L177) when collecting samples for Hanabi Environment?

```
  def collect(self, step):
      for current_agent_id in range(self.num_agents):
          ...
          # rearrange reward
          # reward of step 0 will be thrown away.
          self.turn_rewards[choose, current_agent_id] = self.turn_rewards_since_last_action[choose, current_agent_id].copy()
          self.turn_rewards_since_last_action[choose, current_agent_id] = 0.0
          self.turn_rewards_since_last_action[choose] += rewards[choose]
          ...
```

**Comment by zoeyuchao** [comment]
because hanabi is a turn-based game, the reward of step 0 is a fake one, the true reward should be the accumulated step reward after one turn.
