### ISSUE TITLE
A few questions about death masking

### ISSUE THREAD

**Issue by Denys88** [marlbenchmark/on-policy#34]
Could you confirm if I understood it right according to https://github.com/marlbenchmark/on-policy/issues/1:

1) You return death mask which is used only for policy to calculate advantages, policy loss and entropy plus change global state for agent. And thats all? I tried similar thing with IPPO and didn't work good.

2) Could you point out to the feature pruning vs default env global state in the code? 

Thanks,
Denys

**Comment by zoeyuchao** [comment]
if u want to try IPPO, add --share_policy in the training script, the algorithm will turn to use independent PPO. The results should be consistent with those we reported in our paper.

**Comment by zoeyuchao** [comment]
As for the second question, u can refer to this function https://github.com/marlbenchmark/on-policy/blob/9677c91ff7de0defc245f65c1ea31c8587df162a/onpolicy/envs/starcraft2/StarCraft2_Env.py#L1327
