### ISSUE TITLE
 continuous action space

### ISSUE THREAD

**Issue by ollehhello** [marlbenchmark/on-policy#36]
Hi, can MAPPO be used for continuous action space? How can I do this?When I change discrete_action under environment.py to False, the following error will appear.
![image](https://user-images.githubusercontent.com/48572954/160048129-7b5077fa-1fef-4c54-8fc6-857a54d9dd69.png)

**Comment by wanghui589** [comment]
I have the same problem, has anyone solved it?

**Comment by sinizu** [comment]
> I have the same problem, has anyone solved it?

https://github.com/marlbenchmark/on-policy/blob/9677c91ff7de0defc245f65c1ea31c8587df162a/onpolicy/algorithms/utils/distributions.py#L82

it should be modified.

**Comment by Shenyiou** [comment]
> 

but what to change? the codes below only need x

**Comment by sinizu** [comment]
> > 
> 
> but what to change? the codes below only need x
maybe:
python '''
def forward(self, x, a=None):

**Comment by Shenyiou** [comment]
> > but what to change? the codes below only need x
> > maybe:
> > python '''
> > def forward(self, x, a=None):
> > '''

sorry, it doesn't work

Traceback (most recent call last):
  File "/home/qss/syo/onpolicy/scripts/train/train_mpe.py", line 169, in <module>
    main(sys.argv[1:])
  File "/home/qss/syo/onpolicy/scripts/train/train_mpe.py", line 154, in main
    runner.run()
  File "/home/qss/syo/onpolicy/runner/shared/mpe_runner.py", line 28, in run
    values, actions, action_log_probs, rnn_states, rnn_states_critic, actions_env = self.collect(step)
  File "/home/qss/.conda/envs/syo/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "/home/qss/syo/onpolicy/runner/shared/mpe_runner.py", line 121, in collect
    raise NotImplementedError
NotImplementedError

**Comment by sinizu** [comment]
> 

https://github.com/marlbenchmark/on-policy/blob/9677c91ff7de0defc245f65c1ea31c8587df162a/onpolicy/runner/shared/mpe_runner.py#L121

___________________________
The code above also needs to be changed
```python
# raise NotImplementedError
pass
```

**Comment by Shenyiou** [comment]
@sinizu would you mind give me your emal please. there are still  some problems i want to talk with you.

**Comment by chillybird** [comment]
> 

You can develop it just like discrete action implement. But i can not get satisfied result when i use the modified code.

**Comment by sinizu** [comment]
> @sinizu would you mind give me your emal please. there are still some problems i want to talk with you.

You can leave yours. I'll text you when I'm free

**Comment by Shenyiou** [comment]
> You can leave yours. I'll text you when I'm free

thank a lot! I've successfully changed it to continuous action space. however the result is slightly inferior compared with discrete version.

**Comment by kargarisaac** [comment]
@Shenyiou 
would you mind share your code or tell what you have changed? That would help a lot
