### ISSUE TITLE
How to train MAPPO on MPE with the separated policy?

### ISSUE THREAD

**Issue by whz204168-lab** [marlbenchmark/on-policy#37]
I have trained MAPPO on simple_spread with the separated policy, but the results are not stable. 
Could the authors help me explain the problem of hyperparameter settings?

**Comment by zoeyuchao** [comment]
can u upload ur hyperparameters setting? like the training scripts.

**Comment by whz204168-lab** [comment]
I have solved this problem. Thank you very much.
