### ISSUE TITLE
Why use self.buffer[agent_id].after_update()?

### ISSUE THREAD

**Issue by LiZhYun** [marlbenchmark/on-policy#38]
def train(self):
        train_infos = []
        for agent_id in range(self.num_agents):
            self.trainer[agent_id].prep_training()
            train_info = self.trainer[agent_id].train(self.buffer[agent_id])
            train_infos.append(train_info)       
            self.buffer[agent_id].after_update()

        return train_infos

why use after_update() after train()?

**Comment by zoeyuchao** [comment]
We move the data of the last step to the first step in afer_update() function, u can treat it as the data warmup.

**Comment by LiZhYun** [comment]
> 

But the buffer is replaced with new data.

**Comment by LiZhYun** [comment]
Now I see. Thank you.

**Comment by ColdFrenzy** [comment]
@LiZhYun I was trying to understand it too, but it's still not clear to me. Could you explain, please?

**Comment by LiZhYun** [comment]
> 

My personal understanding is that after each episode, the environment does not necessarily end. The agent needs to get the next action from the observation at the end of the previous episode, so it needs to copy  the buffer[-1] to buffer[0]

**Comment by ColdFrenzy** [comment]
Oh, I didn't consider this eventuality, now it's clear. Thank you
