### ISSUE TITLE
In the definition of FixedNormal class have some wrong code.

### ISSUE THREAD

**Issue by chillybird** [marlbenchmark/on-policy#39]
`# Normal` 
`class FixedNormal(torch.distributions.Normal):` 
`    def log_probs(self, actions):` 
`        return super().log_prob(actions).sum(-1, keepdim=True)` 
`    def entrop(self):` 
`        return super.entropy().sum(-1)` 
`    def mode(self):` 
`        return self.mean`

**Comment by chillybird** [comment]
class method entrop is wrong.

**Comment by chillybird** [comment]
I just found that the modified code is wrong, so the code with continuous action can not be modified.

**Comment by chillybird** [comment]
If you change it, you can't get the correct entropy.

**Comment by zoeyuchao** [comment]
ic, thanks
