### ISSUE TITLE
wandb error

### ISSUE THREAD

**Issue by Amanda-1997** [marlbenchmark/on-policy#4]
I met the error： wandb: ERROR Error while calling W&B API: project not found (<Response [404]>)

I have changed the `config.py` about the `--user-name` to mine, but it doesn't work either.

Thank you for your reply.

**Comment by zoeyuchao** [comment]
If u are not familiar with wandb, you can just add `--use_wandb` in the training script and the u will use tensorboard instead. The error says you can not access to the project to log in the data, my advice is you can double check the ip&account.
