### ISSUE TITLE
Using a global state 

### ISSUE THREAD

**Issue by SamueleBolotta** [marlbenchmark/on-policy#42]
In the config.py file, there is this env parameter:

```
    parser.add_argument("--use_obs_instead_of_state", action='store_true',
                        default=False, help="Whether to use global state or concatenated obs")
```

I would like to use a global state in my code. However, I don't understand how the aforementioned parameter is being used, since the base_runner is the only script that extracts it (but then doesn't use it anyway). Thanks!

**Comment by zoeyuchao** [comment]
this is for ablation study of global state, i delete the code when publishing the repo.
