### ISSUE TITLE
VecEnvWrapper is not defined in env_wrappers.py

### ISSUE THREAD

**Issue by SamueleBolotta** [marlbenchmark/on-policy#44]

**Comment by zoeyuchao** [comment]
Thanks, and could u point out where the VecEnvWrapper is used?

**Comment by SamueleBolotta** [comment]
https://github.com/marlbenchmark/on-policy/blob/45a13c6de9cd5a6332ebf9a709cc80e880dc5052/onpolicy/envs/env_wrappers.py#L128

**Comment by zoeyuchao** [comment]
Thanks for pointing out that, this function is not used actually, I will delete it.
