### ISSUE TITLE
Being confused about The huber_loss 

### ISSUE THREAD

**Issue by Atan03** [marlbenchmark/on-policy#47]
the function huber_loss in utils is like:
```
def huber_loss(e, d):
    a = (abs(e) <= d).float()
    b = (e > d).float()
    return a*e**2/2 + b*d*(abs(e)-d/2)
```
It may come with a zero loss when error is greater than huber_delta.

If I'm not mistaken，it should be 
`b = (abs(e) > d).float()`

Looking forward to hearing from you.

**Comment by zoeyuchao** [comment]
Yes, thanks for pointing that, already fixed it.
