### ISSUE TITLE
PopArt implementation is much different from the paper you cited !

### ISSUE THREAD

**Issue by Triple-ROCK** [marlbenchmark/on-policy#5]
I just read about the original paper that come up with "PopArt", their idea is mainly to keep the normalization factors from affecting learning process by modfying "W, b" of the last layer, but your implementation is just a z-transformation for value normalization, which actually hurts training in my experiments. Maybe you should respect the original PopArt paper?

**Comment by zoeyuchao** [comment]
I have tried the "improved PopArt" and it reached the same performance as "Value Normalization" finally. The reason why we only release VN code is we found PopArt learns a little bit slowly and unstably at the very very beginning (such as the first update iteration). As for the harmful phenomenon you mentioned in your task, I want to confirm whether you are using our code or implemented by yourself? In fact, I've tested PopArt or VN in over 10 MARL domains or tasks with our codebase, and they're really harmless, and have become our default options. Maybe you should double check your code and draw the conclusion carefully?
