### ISSUE TITLE
Clarification on Environment Names

### ISSUE THREAD

**Issue by aravindvenu7** [marlbenchmark/on-policy#54]
What is the difference between Hanabi-Full and Hanabi-very-small?

**Comment by zoeyuchao** [comment]
Hanabi-Full is the official challenge of the Hanabi game, which contains 2-5 players and a max of 25 scores. Hanabi-very-small is a simplified Hanabi game and is only used for testing, which contains 2-5 players but a max of 10 scores.

**Comment by aravindvenu7** [comment]
Thank you!
