### ISSUE TITLE
Can you open-source MASAC code base?

### ISSUE THREAD

**Issue by kailashg26** [marlbenchmark/on-policy#57]
Hello,
Thanks for open-sourcing a really good work. I was wondering if you guys can open-source the MASAC code base as it would help to understand the variations of MASAC with MADDPG and MAPPO. Thanks, in advance for the help.

**Comment by eugenevinitsky** [comment]
We've avoided open-sourcing this as it has gotten quite bad results so we can't be 100% confident that it is implemented correctly. If we open-source it folks will likely use it despite that warning and it may cause issues
