### ISSUE TITLE
Reproducing IPPO results. 

### ISSUE THREAD

**Issue by RuanJohn** [marlbenchmark/on-policy#59]
Hi there, well done on a great paper! 

A question around the results. If I want to reproduce the results obtained for IPPO (particularly on SMAC), what process should I follow? It seems that `cent_obs` should just be set to `False`. Or are there other details required?

**Comment by zoeyuchao** [comment]
i have updated the script, feel free to try that. IPPO is to set `use_centralized_V` to be False.
