### ISSUE TITLE
Time consumption of Hanabi

### ISSUE THREAD

**Issue by Nickydusk** [marlbenchmark/on-policy#62]
When I tried to run Hanabi experiments, I was shocked by the time consumption. The CPU I use is **12th Gen Intel(R) Core(TM) i9-12900K** and GPU is **NVIDIA RTX A5000**, neither of which is running at full capacity (approx. 25% - 70%). I use the default parameters in `train_hanabi_forward.sh`：

```shell
python train/train_hanabi_forward.py --env_name ${env} --algorithm_name ${algo} --experiment_name ${exp} --hanabi_name ${hanabi} --num_agents ${num_agents} --seed 4 --n_training_threads 128 --n_rollout_threads 1000 --n_eval_rollout_threads 32 --num_mini_batch 1 --episode_length 100 --num_env_steps 10000000000000 --ppo_epoch 15 --gain 0.01 --lr 7e-4 --critic_lr 1e-3 --hidden_size 512 --layer_N 2 --use_eval --use_recurrent_policy --entropy_coef 0.015 
```

With this setting, the running FPS is about **3000**, meaning it takes **900+ hours** to reach the **10B** timesteps in the text, i.e. over a month. Is this time consumption consistent with your experience? If not, is there any advice that may fix my problem and improve efficiency?

**Comment by zoeyuchao** [comment]
Yes, it needs ~1 month to reach that timesteps, so we use distributed resources to run more seeds.

**Comment by Nickydusk** [comment]
Thanks~

**Comment by yanxue7** [comment]
I am also confused about how much time is needed for hanabi, if I directly run ./train_hanabi_forward.sh?
with command:
    CUDA_VISIBLE_DEVICES=0 python train/train_hanabi_forward.py --env_name ${env} --algorithm_name ${algo} --experiment_name ${exp} \
    --hanabi_name ${hanabi} --num_agents ${num_agents} --seed ${seed} --n_training_threads 1 --n_rollout_threads 1000 \
    --num_mini_batch 1 --episode_length 100 --num_env_steps 10000000000000 --ppo_epoch 15 \
    --gain 0.01 --lr 7e-4 --critic_lr 1e-3 --hidden_size 512 --layer_N 2 --entropy_coef 0.015 
    echo "training is done!"

**Comment by yanxue7** [comment]
And the training process seems stuck？


(mappo) root@b87359ee5a59:/mnt/nasdata/xxx/mappo/onpolicy/scripts# sh train_hanabi_forward.sh env is Hanabi, algo is mappo, exp is check, max seed is 1
seed is 1:c
u are choosing to use mappo, we set use_recurrent_policy & use_naive_recurrent_policy to be False
choose to use gpu...
