### ISSUE TITLE
[Environment] gfootball verision

### ISSUE THREAD

**Issue by LXXXXR** [marlbenchmark/on-policy#65]
Hi,

Thank you for the wonderful work.

May I ask which version of google football this repo is based on? It seems that not all the scenarios are in the newest version of google football.

Thank you.

**Comment by zoeyuchao** [comment]
I use the default version. could u tell me which one is missing?

**Comment by LXXXXR** [comment]
Thank you for the reply.

For example, in your [scripts](https://github.com/marlbenchmark/on-policy/blob/main/onpolicy/scripts/train_football_scripts/train_football_rp.sh), one scenario called "academy_run_and_pass_with_keeper" is no longer available in [google football](https://github.com/google-research/football/tree/master/gfootball/scenarios). So I was just curious which version you used for this repo dependency.

It's probably because the changes happen in gfootball. Moreover, I also experienced some slight issues with some of the variables type in the environment class using the newest version, i.e. v2.10.2. But minor modifications to the codes can fix that. 

Thanks again!

**Comment by zoeyuchao** [comment]
I just check it out, the version i used is 2.10.1. FYI.

**Comment by LXXXXR** [comment]
Thanks
