### ISSUE TITLE
terminal error-render_mpe.sh

### ISSUE THREAD

**Issue by EddyJason** [marlbenchmark/on-policy#67]
I met the troble with the terminal. I can run the train_mpe.py, but I can not run the render_mpe.sh. The terminla proposed the error: 
env is MPE
Traceback (most recent call last):
  File "render/render_mpe.py", line 12, in <module>
    from onpolicy.config import get_config
**ModuleNotFoundError: No module named 'onpolicy'**
But  the module is not wrong.

**Comment by XHN-1** [comment]
Reinstall the onpolicy package
``` bash
cd on-policy
pip install -e .
```

**Comment by chatsmile** [comment]
我运行render_mpe.sh时遇到了问题，报错如下
No such file or directory: 'xxx/actor_agent0.pt'
我不知道如何修正。

**Comment by ycslnc** [comment]
你好，我也遇到了这个问题，请问你解决了吗？

**Comment by chatsmile** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
