### ISSUE TITLE
envs reset in data-collecting and evaluation period

### ISSUE THREAD

**Issue by FisherguanbaoYu** [marlbenchmark/on-policy#7]
Both in data collecting and evaluation period, when an episode terminated, the model just take the last obs of corresponding env as input. But i think the envs should be reset if reach termination. Or i missed something in the code?

**Comment by zoeyuchao** [comment]
Yes, you missed the reset code. see here: https://github.com/marlbenchmark/on-policy/blob/83cd4d5f5a91b473fedddeab6251d4dcd206fe57/onpolicy/envs/env_wrappers.py#L148

**Comment by FisherguanbaoYu** [comment]
> Yes, you missed the reset code. see here:
> 
> https://github.com/marlbenchmark/on-policy/blob/83cd4d5f5a91b473fedddeab6251d4dcd206fe57/onpolicy/envs/env_wrappers.py#L148

i c! Thanks for your quick reply!

**Comment by hccz95** [comment]
> Yes, you missed the reset code. see here:
> 
> https://github.com/marlbenchmark/on-policy/blob/83cd4d5f5a91b473fedddeab6251d4dcd206fe57/onpolicy/envs/env_wrappers.py#L148

in mpe, the `done` flag is not true, we need reset by ourselves?
