### ISSUE TITLE
bug in football_runner.py

### ISSUE THREAD

**Issue by Random8756** [marlbenchmark/on-policy#72]
Line 135: "rnn_states=rnn_states"
Class FootballRunner inherits from class Runner and Runner inherits from class SharedReplayBuffer.
The func "insert()" with parameter "rnn_states_actor"(line 79 in shared_buffer.py) is inconsistent with football_runner.py "rnn_states=rnn_states", which may incur an error: "got an unexpected keyword argument "rnn_states".

**Comment by HosnLS** [comment]
Thank you for reporting the bug. A new PR has been raised.
