### ISSUE TITLE
How to speed up training on hanabi

### ISSUE THREAD

**Issue by yanxue7** [marlbenchmark/on-policy#73]
I run the below command on 256 core CPU and A100 40GX2. But the FPS is only 1377, I am confused about how can I seed up the training on Hananbi.
python train/train_hanabi_forward.py --env_name ${env} --algorithm_name ${algo} --experiment_name ${exp} \
    --hanabi_name ${hanabi} --num_agents ${num_agents} --seed ${seed} --n_training_threads 1 --n_rollout_threads 5000 \
    --num_mini_batch 128 --episode_length 100 --num_env_steps 10000000000000 --ppo_epoch 15 \
    --gain 0.01 --lr 7e-4 --critic_lr 1e-3 --hidden_size 512 --layer_N 2 --entropy_coef 0.015

**Comment by HosnLS** [comment]
The `num_mini_batch` is set to 128 and `n_rollout_threads` is set to 5000, which may be too large for this environment. 

Please note that MAPPO will go through all minibatches sequentially in one PPO epoch. So a large `num_mini_batch` may slow down the training process. It is recommended to maintain default args (especially `num_mini_batch`). And moderately increase `n_rollout_threads` is also ok.
