### ISSUE TITLE
How to caculate rewards in MARL environments?

### ISSUE THREAD

**Issue by BUPT-zeld151** [marlbenchmark/on-policy#78]
I wanna ask how you treat with rewards of agents in MARL environments in MAPPO. Assuming there are 2 agents in one environment training, as the README of this algorithm says, they share one neural network on acting and evaluating, am I right? Considering the 2 agents share the same central observations which is a concatenation of their local observations, the critic network should output the same evaluation V(S_t) for each of them at time t. However, each agent would get a unique reward due to its local action, and the local rewards of each agent seem to be processed independently in caculating advantages, would it cause unstability in training the critic network?

**Comment by zoeyuchao** [comment]
In all experiments in the MAPPO paper, the rewards for all agents are shared, meaning they are the same. Additionally, the input to the critic in MAPPO includes the agent's ID or is partially specific to the agent.
