### ISSUE TITLE
Trained Hanabi agents

### ISSUE THREAD

**Issue by ingo-ch** [marlbenchmark/on-policy#8]
Hi

Is it possible to get access to the 4 mappo trained actor and critic models in Hanabi that you refer to in the paper?

Many thanks!

**Comment by zoeyuchao** [comment]
[hanabi_model.zip](https://github.com/marlbenchmark/on-policy/files/6374104/hanabi_model.zip)

**Comment by zoeyuchao** [comment]
I download 2 seeds, FYI.

**Comment by ingo-ch** [comment]
Thank you very much!
