### ISSUE TITLE
render_mpe produces much worse performance than training or evaluation

### ISSUE THREAD

**Issue by LINGYUNFDU** [marlbenchmark/on-policy#84]
Hi,
I have trained the MPE simple-spread task using MAPPO with suggested hyperparameters. As expected, the training and evaluation converge as well as in the paper. 

However, when I render the trained model using render_mpe.sh, it shows a very bad performance. Can you give any advice for the possible reasons?

Best

**Comment by LINGYUNFDU** [comment]
This is solved. I forgot to add "--use_ReLU" when rendering, while in training this argument was used.

**Comment by ycslnc** [comment]
你好，我也遇到了同样的问题，--use_ReLU在config中默认为True，试过你的方法后render效果还是很差，请问你有什么建议吗？

**Comment by wenshuaizhao** [comment]
我也不确定，最好检查下所有的超参数设置，确保跟training的时候都一样

**Comment by zhanshuxie** [comment]
thank you
