### ISSUE TITLE
Doubts about the results of rmappo/mappo in SMAC

### ISSUE THREAD

**Issue by linshi9658** [marlbenchmark/on-policy#85]
Hello,

I tried to use rmappo/mappo to run several experiments on SMAC. The results of rmappo's three experiments in MMM2 are exactly the same (the curves drawn by TensorBoard are completely coincident). This phenomenon also appears on the 8m, 3s_vs_5z, 5m_vs_6m maps. This confuses me, would be very grateful if you could provide some advice.

**Comment by zoeyuchao** [comment]
if you want different curves, you need to use different seeds.
