### ISSUE TITLE
Runtime Error: Tensors on Different Devices (cuda:0 and cpu)

### ISSUE THREAD

**Issue by itstyren** [marlbenchmark/on-policy#89]
### Environment:

Operating System: CentOS Linux release 7.9.2009
Python Version: python 3.10.0
PyTorch Version:  2.0.1  ( py3.10_cuda11.8_cudnn8.7.0_0)

### Description:
I encountered a runtime error in the code when attempting to run the training script `./train_mpe_reference.sh`. The error message indicates that tensors are on different devices, specifically "cuda:0" (GPU) and "cpu," when they should be on the same device. 

### Error Message:
```bash
Traceback (most recent call last):
  File ".../train_mpe.py", line 174, in <module>
    main(sys.argv[1:])
  File ".../train_mpe.py", line 159, in main
    runner.run()
  File ".../mpe_runner.py", line 39, in run
    self.compute()
  File ".../base_runner.py", line 136, in compute
    self.buffer.compute_returns(next_values, self.trainer.value_normalizer)
  File ".../shared_buffer.py", line 236, in compute_returns
    delta = self.rewards[step] + self.gamma * value_normalizer.denormalize(
  File ".../valuenorm.py", line 75, in denormalize
    out = input_vector * torch.sqrt(var)[(None,) * self.norm_axes] + mean[(None,) * self.norm_axes]
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```

Thank you for your help in addressing this issue.

**Comment by kangbeenlee** [comment]
I solved above same problem like below:

in r_mappo.py

if self._use_popart:
    self.value_normalizer = self.policy.critic.v_out
elif self._use_valuenorm:
    # self.value_normalizer = ValueNorm(1).to(self.device)
    self.value_normalizer = ValueNorm(input_shape=1, device=self.device)
else:
    self.value_normalizer = None
            
I think "self.value_normalizer = ValueNorm(1).to(self.device)" do not work properly. Just change this line to "self.value_normalizer = ValueNorm(input_shape=1, device=self.device)"
