### ISSUE TITLE
missing "onpolicy.runner.separated.hanabi_runner_forward"

### ISSUE THREAD

**Issue by AlbertoSinigaglia** [marlbenchmark/on-policy#94]
Hi there  
Thanks for the great repository, one question.  
I see here https://github.com/marlbenchmark/on-policy/blob/4769caf56a9b2ccb90866ae56f1d9c804432e63b/onpolicy/scripts/train/train_hanabi_forward.py#L162 that there is supposed to be a `Runner` for Hanabi separated but I can't find the file, any idea?

**Comment by zoeyuchao** [comment]
We suggest running the Hanabi experiment via shared policy, so we remove the separated runner. It is just a try when we develop this repository.
