### ISSUE TITLE
NAN

### ISSUE THREAD

**Issue by lgzid** [marlbenchmark/on-policy#96]
Hello, I'm training my task using MAPPO and I've noticed a sharp increase in the imp_weights parameter in the actor during training, leading to the occurrence of NaN. How can I resolve this issue, considering that I've already applied gradient clipping?

**Comment by zoeyuchao** [comment]
usually you need to check the obs and  action first to see if you have connected the environment and algo. correctly. Then tune the reward function～发自我的 iPhone在 2023年12月14日，20:56，lgzid ***@***.***> 写道：﻿
Hello, I'm training my task using MAPPO and I've noticed a sharp increase in the imp_weights parameter in the actor during training, leading to the occurrence of NaN. How can I resolve this issue, considering that I've already applied gradient clipping?

**Comment by lgzid** [comment]
OK
Thanks！
