### ISSUE TITLE
When I tried to train the code for smacv2, I encountered this error message——AssertionError: check recurrent policy!

### ISSUE THREAD

**Issue by chenzihan1** [marlbenchmark/on-policy#97]
The detailed errors are as follows：

Traceback (most recent call last):
  File "../train/train_smac.py", line 260, in <module>
    main(sys.argv[1:])
  File "../train/train_smac.py", line 138, in main
    "check recurrent policy!")
AssertionError: check recurrent policy!

What should I do？

**Comment by zoeyuchao** [comment]
just update the code. Try again~btw: just delete assert line
